export const SITE_CONFIG = {
  name: 'Ghurabo',
  domain: 'https://ghurabo.app',
  defaultLocale: 'en',
  locales: ['en', 'bn'],
  tagline: {
    en: 'Real Trips. Real Costs. Real Experiences.',
    bn: 'বাস্তব ট্রিপ, বাস্তব খরচ, বাস্তব অভিজ্ঞতা।',
  },
  description: {
    en: 'Discover real Bangladesh trips, routes, expense breakdowns, photos and practical travel advice shared by real travelers.',
    bn: 'বাস্তব ভ্রমণকারীদের শেয়ার করা ট্রিপ, যাতায়াত, জনপ্রতি খরচ, ছবি ও প্রয়োজনীয় পরামর্শ দেখে বাংলাদেশের পরবর্তী ভ্রমণ পরিকল্পনা করুন।',
  },
  keywords: {
    en: [
      'Bangladesh travel',
      'Bangladesh travel guide',
      'Bangladesh trip cost',
      'Budget travel Bangladesh',
      'Bangladesh tour plan',
      'Real trip cost Bangladesh',
      'Bangladesh travel experience',
      'Bangladesh travel community',
      'Places to visit in Bangladesh',
      'Low budget trips in Bangladesh',
      'Weekend trips from Dhaka',
      'Family trips in Bangladesh',
      'Couple trips in Bangladesh',
      'Student budget trips Bangladesh',
      'Solo travel Bangladesh',
    ],
    bn: [
      'বাংলাদেশ ভ্রমণ',
      'বাংলাদেশ ভ্রমণ গাইড',
      'ভ্রমণ খরচ',
      'কম খরচে ভ্রমণ',
      'বাজেট ট্যুর বাংলাদেশ',
      'বাস্তব ভ্রমণ অভিজ্ঞতা',
      'ট্রিপ প্ল্যান বাংলাদেশ',
      'বাংলাদেশে দর্শনীয় স্থান',
      'কোথায় ঘুরতে যাব',
      'ঢাকা থেকে কম খরচে ভ্রমণ',
      'ছাত্রদের বাজেট ট্যুর',
      'কাপল ট্যুর বাংলাদেশ',
      'ফ্যামিলি ট্যুর বাংলাদেশ',
      'একদিনের ভ্রমণ',
      'দুই দিনের ট্যুর প্ল্যান',
      'জনপ্রতি ভ্রমণ খরচ',
    ],
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://ghurabo.app',
    siteName: 'Ghurabo',
    images: [
      {
        url: 'https://ghurabo.app/images/sajek_cloud_valley.png',
        width: 1200,
        height: 630,
        alt: 'Ghurabo — Real Trips. Real Costs. Real Experiences.',
      },
    ],
  },
};
